theme: jekyll-theme-primer
repository: davecheng-tech/Class-Notes-and-Addenda
title: ""
show_downloads: false
plugins:
  - jekyll-gfm-admonitions
  - jekyll-optional-front-matter
defaults:
  - scope:
      path: ""
    values:
      layout: default